### ISSUE TITLE
Undeclared dependency on monex causes error

### ISSUE THREAD

**Issue by joewiz** [eXist-db/usermanager#13]
When a user starts up a fresh installation of eXist 4.0.0 with usermanager in the autodeploy directory, an error appears in exist.log (see below). I traced this to `modules/usermanager.xqm`, which [imports the console module](https://github.com/eXist-db/usermanager/blob/6ea604ba04c4054e675581180729dd7760d56a40/modules/userManager.xqm#L36) from monex. eXist checks for the presence of this module's imported modules during installation of the app because this module is a RESTXQ module. 

The solution is to add the following to the app's [expath-pkg.xml](https://github.com/eXist-db/usermanager/blob/master/expath-pkg.xml) file:

```xml
<dependency package="http://exist-db.org/apps/monex"/>
```

Error in exist.log:

```text
2018-02-15 01:05:19,372 [Thread-2] ERROR (DocumentTriggers.java [afterCreateDocument]:238) - Invalid URI: xmldb URI scheme does not start with xmldb:: http://exist-db.org/xquery/console 
java.lang.IllegalArgumentException: Invalid URI: xmldb URI scheme does not start with xmldb:: http://exist-db.org/xquery/console
	at org.exist.xmldb.XmldbURI.create(XmldbURI.java:219) ~[exist.jar:4.0.0]
	at org.exist.xmldb.XmldbURI.append(XmldbURI.java:595) ~[exist.jar:4.0.0]
	at org.exist.extensions.exquery.restxq.impl.ExistXqueryRegistry.getAbsoluteModuleHint(ExistXqueryRegistry.java:453) ~[exist-restxq.jar:4.0.0]
	at org.exist.extensions.exquery.restxq.impl.ExistXqueryRegistry.recordMissingDependency(ExistXqueryRegistry.java:410) ~[exist-restxq.jar:4.0.0]
	at org.exist.extensions.exquery.restxq.impl.ExistXqueryRegistry.findServices(ExistXqueryRegistry.java:255) ~[exist-restxq.jar:4.0.0]
	at org.exist.extensions.exquery.restxq.impl.RestXqTrigger.after(RestXqTrigger.java:113) ~[exist-restxq.jar:4.0.0]
	at org.exist.extensions.exquery.restxq.impl.RestXqTrigger.afterCreateDocument(RestXqTrigger.java:51) ~[exist-restxq.jar:4.0.0]
	at org.exist.collections.triggers.DocumentTriggers.afterCreateDocument(DocumentTriggers.java:236) ~[exist.jar:4.0.0]
	at org.exist.collections.MutableCollection.addBinaryResource(MutableCollection.java:1712) ~[exist.jar:4.0.0]
	at org.exist.collections.MutableCollection.addBinaryResource(MutableCollection.java:1646) ~[exist.jar:4.0.0]
	at org.exist.collections.MutableCollection.addBinaryResource(MutableCollection.java:1640) ~[exist.jar:4.0.0]
	at org.exist.repo.Deployment.storeFiles(Deployment.java:810) ~[exist.jar:4.0.0]
	at org.exist.repo.Deployment.scanDirectory(Deployment.java:727) ~[exist.jar:4.0.0]
	at org.exist.repo.Deployment.lambda$scanDirectory$20(Deployment.java:732) ~[exist.jar:4.0.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_162]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_162]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_162]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_162]
	at org.exist.repo.Deployment.scanDirectory(Deployment.java:732) ~[exist.jar:4.0.0]
	at org.exist.repo.Deployment.scanDirectory(Deployment.java:699) ~[exist.jar:4.0.0]
	at org.exist.repo.Deployment.deploy(Deployment.java:446) ~[exist.jar:4.0.0]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:282) ~[exist.jar:4.0.0]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:164) ~[exist.jar:4.0.0]
	at org.exist.repo.Deployment.installAndDeploy(Deployment.java:251) ~[exist.jar:4.0.0]
	at org.exist.repo.AutoDeploymentTrigger.execute(AutoDeploymentTrigger.java:93) ~[exist.jar:4.0.0]
	at org.exist.storage.StartupTriggersManager.startPreMultiUserSystem(StartupTriggersManager.java:58) ~[exist.jar:4.0.0]
	at org.exist.storage.BrokerPoolServicesManager.startPreMultiUserSystemServices(BrokerPoolServicesManager.java:212) ~[exist.jar:4.0.0]
	at org.exist.storage.BrokerPool._initialize(BrokerPool.java:631) ~[exist.jar:4.0.0]
	at org.exist.storage.BrokerPool.initialize(BrokerPool.java:415) ~[exist.jar:4.0.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:181) ~[exist.jar:4.0.0]
	at org.exist.storage.BrokerPools.configure(BrokerPools.java:110) ~[exist.jar:4.0.0]
	at org.exist.jetty.JettyStart.run(JettyStart.java:169) ~[exist-optional.jar:4.0.0]
	at org.exist.launcher.Launcher.lambda$startJetty$2(Launcher.java:165) ~[exist.jar:4.0.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by dizzzz** [comment]
interesting.... as my clean install seem to work fine... will continue checking....

**Comment by joewiz** [comment]
If monex is auto deployed first, you won’t see this. You can simulate this by removing monex from your autodeploy directory (for certain, it happens if you remove all apps but user manager). But on my system user manager was being installed first before monex.

**Comment by dizzzz** [comment]
yes i confirm..... so we should rename monex to 00monex in the autodeploy folder?

**Comment by joewiz** [comment]
Could this not be solved by apps like this declaring their dependencies in expath-pkg.xml? Apps are pretty good about declaring their dependence on shared-resources, so I am curious why shared-resources is prepended with 00?

**Comment by wolfgangmm** [comment]
Yes, either usermanager declares a dependency or the console:log statements have to be removed.

**Comment by JoernT** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/oDIo1zYc/1-test)

**Comment by JoernT** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/oDIo1zYc/1-test)

**Comment by peterstadler** [comment]
Just hit that issue in a recent 5.3.0-SNAPSHOT (Docker version). Is that a regression or some other issue?

### The error messages on startup:
` Invalid URI: xmldb URI scheme does not start with xmldb:: http://exist-db.org/xquery/console`

### The cure
adding dependency on monex

### System specs
Dashboard Version 2.0.6
eXist Version : 5.3.0-SNAPSHOT
eXist Build : 20200615103146
Git commit : 257da6f35b5938f982899e88b5f31cbee88d0f36
Operating System : Linux 4.19.76-linuxkit amd64
Running with Java 1.8.0_252 [Oracle Corporation (OpenJDK 64-Bit Server VM)
